#
# This is a generated file.
#

api.version=v1.0
entity.class.name=com.liferay.content.composer.rest.dto.v1_0.Composition
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Content.Composer.REST)
osgi.jaxrs.resource=true